SELECT C.CAR_ID, C.CAR_TYPE,
    FLOOR(C.DAILY_FEE * 0.3 * (100-D.RATE)) AS FEE
FROM CAR_RENTAL_COMPANY_CAR C
    JOIN (SELECT CAR_TYPE, DISCOUNT_RATE AS RATE
          FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
          WHERE DURATION_TYPE = '30일 이상') D
        ON C.CAR_TYPE = D.CAR_TYPE
WHERE CAR_ID NOT IN (SELECT CAR_ID
                     FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                     WHERE START_DATE <= '2022-11-30'
                         AND END_DATE  >= '2022-11-01')
    AND 500000 <= C.DAILY_FEE * 0.3 * (100-D.RATE)
    AND C.DAILY_FEE * 0.3 * (100-D.RATE) < 2000000
ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC
