SELECT CART_ID
FROM CART_PRODUCTS
WHERE CART_ID IN (SELECT CART_ID
                  FROM CART_PRODUCTS
                  WHERE NAME = 'Milk')
    AND CART_ID IN (SELECT CART_ID
               FROM CART_PRODUCTS
               WHERE NAME = 'Yogurt')
GROUP BY CART_ID
ORDER BY CART_ID;

-- INNER JOIN 이용하는 방식
SELECT DISTINCT M.CART_ID
FROM CART_PRODUCTS M
JOIN CART_PRODUCTS Y ON M.CART_ID = Y.CART_ID
WHERE M.NAME = 'Milk' AND Y.NAME = 'Yogurt'
ORDER BY M.CART_ID;
