SELECT I.REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS,
    ROUND(AVG(R.REVIEW_SCORE), 2) AS SCORE
FROM REST_INFO I
    JOIN (SELECT REST_ID, REVIEW_SCORE
         FROM REST_REVIEW) R
        ON I.REST_ID = R.REST_ID
WHERE ADDRESS LIKE '서울%'
GROUP BY REST_ID
ORDER BY SCORE DESC, FAVORITES DESC;

/*
ADDRESS = 서울
리뷰 평균 점수 SCORE
*/
