SELECT A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY,
    SUM(B.PRICE*S.SALES) AS TOTAL_SALES
FROM BOOK B
    JOIN (SELECT BOOK_ID, SUM(SALES) AS SALES
          FROM BOOK_SALES
          WHERE SALES_DATE>='2022-01-01'
              AND SALES_DATE<'2022-02-01'
          GROUP BY BOOK_ID) S
        ON B.BOOK_ID = S.BOOK_ID
    JOIN AUTHOR A
        ON B.AUTHOR_ID = A.AUTHOR_ID
GROUP BY AUTHOR_ID, CATEGORY
ORDER BY AUTHOR_ID, CATEGORY DESC;
