SELECT C.CAR_ID, C.CAR_TYPE,
    FLOOR(C.DAILY_FEE * 0.3 * (100-P.DISCOUNT_RATE)) AS FEE
FROM CAR_RENTAL_COMPANY_CAR C
    JOIN (SELECT CAR_TYPE, DISCOUNT_RATE
         FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
         WHERE DURATION_TYPE = '30일 이상') P
        ON C.CAR_TYPE = P.CAR_TYPE
WHERE C.CAR_ID NOT IN (SELECT CAR_ID
                      FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                      WHERE START_DATE<='2022-11-30'
                          AND END_DATE>='2022-11-01')
    AND C.DAILY_FEE * 0.3 * (100-P.DISCOUNT_RATE) >= 500000
    AND C.DAILY_FEE * 0.3 * (100-P.DISCOUNT_RATE) < 2000000
    AND (C.CAR_TYPE = '세단' OR C.CAR_TYPE = 'SUV')
ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC;

/*
CAR_TYPE = '세단' OR 'SUV'
AND CAR_ID NOT IN START_DATE<='2022-11-30' AND END_DATE>='2022-11-01'
AND 30일 FEE>=50만 AND FEE<200만
JOIN PLAN ON CAR_TYPE
*/
